/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.496+a2635268
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Application version.
 * @export
 * @interface AppVersion
 */
export interface AppVersion {
    /**
     * Application version.
     * @type {string}
     * @memberof AppVersion
     */
    version: string;
}

/**
 * Check if a given object implements the AppVersion interface.
 */
export function instanceOfAppVersion(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "version" in value;

    return isInstance;
}

export function AppVersionFromJSON(json: any): AppVersion {
    return AppVersionFromJSONTyped(json, false);
}

export function AppVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppVersion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': json['version'],
    };
}

export function AppVersionToJSON(value?: AppVersion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
    };
}

