/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.496+a2635268
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ChangeStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type ChangeStatus = typeof ChangeStatus[keyof typeof ChangeStatus];


export function ChangeStatusFromJSON(json: any): ChangeStatus {
    return ChangeStatusFromJSONTyped(json, false);
}

export function ChangeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeStatus {
    return json as ChangeStatus;
}

export function ChangeStatusToJSON(value?: ChangeStatus | null): any {
    return value as any;
}

