/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.559+e6531977
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSubmissionCommand
 */
export interface CreateSubmissionCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateSubmissionCommand
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubmissionCommand
     */
    definitionUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubmissionCommand
     */
    contents?: string | null;
}

/**
 * Check if a given object implements the CreateSubmissionCommand interface.
 */
export function instanceOfCreateSubmissionCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateSubmissionCommandFromJSON(json: any): CreateSubmissionCommand {
    return CreateSubmissionCommandFromJSONTyped(json, false);
}

export function CreateSubmissionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubmissionCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'definitionUuid': !exists(json, 'definitionUuid') ? undefined : json['definitionUuid'],
        'contents': !exists(json, 'contents') ? undefined : json['contents'],
    };
}

export function CreateSubmissionCommandToJSON(value?: CreateSubmissionCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'definitionUuid': value.definitionUuid,
        'contents': value.contents,
    };
}

