/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.556+c0267cc6
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDefinitionCommand
 */
export interface CreateDefinitionCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateDefinitionCommand
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDefinitionCommand
     */
    contents?: string | null;
}

/**
 * Check if a given object implements the CreateDefinitionCommand interface.
 */
export function instanceOfCreateDefinitionCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateDefinitionCommandFromJSON(json: any): CreateDefinitionCommand {
    return CreateDefinitionCommandFromJSONTyped(json, false);
}

export function CreateDefinitionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDefinitionCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'contents': !exists(json, 'contents') ? undefined : json['contents'],
    };
}

export function CreateDefinitionCommandToJSON(value?: CreateDefinitionCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'contents': value.contents,
    };
}

