/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.559+e6531977
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChangeStatus } from './ChangeStatus';
import {
    ChangeStatusFromJSON,
    ChangeStatusFromJSONTyped,
    ChangeStatusToJSON,
} from './ChangeStatus';

/**
 * 
 * @export
 * @interface DefinitionChange
 */
export interface DefinitionChange {
    /**
     * 
     * @type {string}
     * @memberof DefinitionChange
     */
    uuid: string;
    /**
     * 
     * @type {Date}
     * @memberof DefinitionChange
     */
    timestamp: Date;
    /**
     * 
     * @type {ChangeStatus}
     * @memberof DefinitionChange
     */
    changeStatus: ChangeStatus;
    /**
     * 
     * @type {string}
     * @memberof DefinitionChange
     */
    contents: string;
}

/**
 * Check if a given object implements the DefinitionChange interface.
 */
export function instanceOfDefinitionChange(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "changeStatus" in value;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function DefinitionChangeFromJSON(json: any): DefinitionChange {
    return DefinitionChangeFromJSONTyped(json, false);
}

export function DefinitionChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionChange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'timestamp': (new Date(json['timestamp'])),
        'changeStatus': ChangeStatusFromJSON(json['changeStatus']),
        'contents': json['contents'],
    };
}

export function DefinitionChangeToJSON(value?: DefinitionChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'timestamp': (value.timestamp.toISOString()),
        'changeStatus': ChangeStatusToJSON(value.changeStatus),
        'contents': value.contents,
    };
}

