/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.496+a2635268
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DefinitionSummary } from './DefinitionSummary';
import {
    DefinitionSummaryFromJSON,
    DefinitionSummaryFromJSONTyped,
    DefinitionSummaryToJSON,
} from './DefinitionSummary';

/**
 * 
 * @export
 * @interface DefinitionSummaryPagedResult
 */
export interface DefinitionSummaryPagedResult {
    /**
     * 
     * @type {Array<DefinitionSummary>}
     * @memberof DefinitionSummaryPagedResult
     */
    items: Array<DefinitionSummary>;
    /**
     * 
     * @type {number}
     * @memberof DefinitionSummaryPagedResult
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof DefinitionSummaryPagedResult
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof DefinitionSummaryPagedResult
     */
    totalCount: number;
}

/**
 * Check if a given object implements the DefinitionSummaryPagedResult interface.
 */
export function instanceOfDefinitionSummaryPagedResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "pageNumber" in value;
    isInstance = isInstance && "totalCount" in value;

    return isInstance;
}

export function DefinitionSummaryPagedResultFromJSON(json: any): DefinitionSummaryPagedResult {
    return DefinitionSummaryPagedResultFromJSONTyped(json, false);
}

export function DefinitionSummaryPagedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionSummaryPagedResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(DefinitionSummaryFromJSON)),
        'pageSize': json['pageSize'],
        'pageNumber': json['pageNumber'],
        'totalCount': json['totalCount'],
    };
}

export function DefinitionSummaryPagedResultToJSON(value?: DefinitionSummaryPagedResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(DefinitionSummaryToJSON)),
        'pageSize': value.pageSize,
        'pageNumber': value.pageNumber,
        'totalCount': value.totalCount,
    };
}

