/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.461+9159d8a8
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefinitionSummary
 */
export interface DefinitionSummary {
    /**
     * 
     * @type {string}
     * @memberof DefinitionSummary
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof DefinitionSummary
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof DefinitionSummary
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the DefinitionSummary interface.
 */
export function instanceOfDefinitionSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function DefinitionSummaryFromJSON(json: any): DefinitionSummary {
    return DefinitionSummaryFromJSONTyped(json, false);
}

export function DefinitionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'title': json['title'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function DefinitionSummaryToJSON(value?: DefinitionSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'title': value.title,
        'timestamp': (value.timestamp.toISOString()),
    };
}

