/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.461+9159d8a8
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefinitionDetails
 */
export interface DefinitionDetails {
    /**
     * 
     * @type {string}
     * @memberof DefinitionDetails
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof DefinitionDetails
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof DefinitionDetails
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof DefinitionDetails
     */
    contents: string;
}

/**
 * Check if a given object implements the DefinitionDetails interface.
 */
export function instanceOfDefinitionDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function DefinitionDetailsFromJSON(json: any): DefinitionDetails {
    return DefinitionDetailsFromJSONTyped(json, false);
}

export function DefinitionDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'title': json['title'],
        'timestamp': (new Date(json['timestamp'])),
        'contents': json['contents'],
    };
}

export function DefinitionDetailsToJSON(value?: DefinitionDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'title': value.title,
        'timestamp': (value.timestamp.toISOString()),
        'contents': value.contents,
    };
}

