/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DefinitionSummary } from './DefinitionSummary';
import {
    DefinitionSummaryFromJSON,
    DefinitionSummaryFromJSONTyped,
    DefinitionSummaryToJSON,
} from './DefinitionSummary';

/**
 * 
 * @export
 * @interface DefinitionSummaryPagedResult
 */
export interface DefinitionSummaryPagedResult {
    /**
     * 
     * @type {Array<DefinitionSummary>}
     * @memberof DefinitionSummaryPagedResult
     */
    items?: Array<DefinitionSummary> | null;
    /**
     * 
     * @type {number}
     * @memberof DefinitionSummaryPagedResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof DefinitionSummaryPagedResult
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof DefinitionSummaryPagedResult
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the DefinitionSummaryPagedResult interface.
 */
export function instanceOfDefinitionSummaryPagedResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DefinitionSummaryPagedResultFromJSON(json: any): DefinitionSummaryPagedResult {
    return DefinitionSummaryPagedResultFromJSONTyped(json, false);
}

export function DefinitionSummaryPagedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionSummaryPagedResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(DefinitionSummaryFromJSON)),
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
    };
}

export function DefinitionSummaryPagedResultToJSON(value?: DefinitionSummaryPagedResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(DefinitionSummaryToJSON)),
        'pageSize': value.pageSize,
        'pageNumber': value.pageNumber,
        'totalCount': value.totalCount,
    };
}

