/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Fair use token, used to control communication on public endpoints.
 * @export
 * @interface FairUseToken
 */
export interface FairUseToken {
    /**
     * Encrypted fair use token.
     * @type {string}
     * @memberof FairUseToken
     */
    token?: string | null;
}

/**
 * Check if a given object implements the FairUseToken interface.
 */
export function instanceOfFairUseToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FairUseTokenFromJSON(json: any): FairUseToken {
    return FairUseTokenFromJSONTyped(json, false);
}

export function FairUseTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): FairUseToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function FairUseTokenToJSON(value?: FairUseToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

