/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.556+c0267cc6
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HealthStatus } from './HealthStatus';
import {
    HealthStatusFromJSON,
    HealthStatusFromJSONTyped,
    HealthStatusToJSON,
} from './HealthStatus';

/**
 * Represents a result in a PommaLabs.Salatino.Models.DataTransferObjects.HealthReport.
 * Corresponds to the result of a single health check.
 * @export
 * @interface HealthReportResult
 */
export interface HealthReportResult {
    /**
     * 
     * @type {HealthStatus}
     * @memberof HealthReportResult
     */
    status?: HealthStatus;
    /**
     * Human-readable description of the status of the component that was checked.
     * @type {string}
     * @memberof HealthReportResult
     */
    description?: string | null;
    /**
     * Health check execution duration, expressed in seconds.
     * @type {number}
     * @memberof HealthReportResult
     */
    duration?: number;
    /**
     * Additional key-value pairs describing the health of the component.
     * @type {{ [key: string]: any; }}
     * @memberof HealthReportResult
     */
    data?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the HealthReportResult interface.
 */
export function instanceOfHealthReportResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthReportResultFromJSON(json: any): HealthReportResult {
    return HealthReportResultFromJSONTyped(json, false);
}

export function HealthReportResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthReportResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : HealthStatusFromJSON(json['status']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function HealthReportResultToJSON(value?: HealthReportResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': HealthStatusToJSON(value.status),
        'description': value.description,
        'duration': value.duration,
        'data': value.data,
    };
}

