/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.559+e6531977
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HealthReportResult } from './HealthReportResult';
import {
    HealthReportResultFromJSON,
    HealthReportResultFromJSONTyped,
    HealthReportResultToJSON,
} from './HealthReportResult';
import type { HealthStatus } from './HealthStatus';
import {
    HealthStatusFromJSON,
    HealthStatusFromJSONTyped,
    HealthStatusToJSON,
} from './HealthStatus';

/**
 * Report produced after running all health checks.
 * @export
 * @interface HealthReport
 */
export interface HealthReport {
    /**
     * 
     * @type {HealthStatus}
     * @memberof HealthReport
     */
    status?: HealthStatus;
    /**
     * Total duration of all health checks, expressed in seconds.
     * @type {number}
     * @memberof HealthReport
     */
    totalDuration?: number;
    /**
     * Results of each health check.
     * @type {Array<HealthReportResult>}
     * @memberof HealthReport
     */
    results?: Array<HealthReportResult> | null;
}

/**
 * Check if a given object implements the HealthReport interface.
 */
export function instanceOfHealthReport(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthReportFromJSON(json: any): HealthReport {
    return HealthReportFromJSONTyped(json, false);
}

export function HealthReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthReport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : HealthStatusFromJSON(json['status']),
        'totalDuration': !exists(json, 'totalDuration') ? undefined : json['totalDuration'],
        'results': !exists(json, 'results') ? undefined : (json['results'] === null ? null : (json['results'] as Array<any>).map(HealthReportResultFromJSON)),
    };
}

export function HealthReportToJSON(value?: HealthReport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': HealthStatusToJSON(value.status),
        'totalDuration': value.totalDuration,
        'results': value.results === undefined ? undefined : (value.results === null ? null : (value.results as Array<any>).map(HealthReportResultToJSON)),
    };
}

