/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.461+9159d8a8
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginAuthCodeVerifiedResult
 */
export interface LoginAuthCodeVerifiedResult {
    /**
     * 
     * @type {string}
     * @memberof LoginAuthCodeVerifiedResult
     */
    accessToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginAuthCodeVerifiedResult
     */
    refreshToken?: string | null;
}

/**
 * Check if a given object implements the LoginAuthCodeVerifiedResult interface.
 */
export function instanceOfLoginAuthCodeVerifiedResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoginAuthCodeVerifiedResultFromJSON(json: any): LoginAuthCodeVerifiedResult {
    return LoginAuthCodeVerifiedResultFromJSONTyped(json, false);
}

export function LoginAuthCodeVerifiedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginAuthCodeVerifiedResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'refreshToken': !exists(json, 'refreshToken') ? undefined : json['refreshToken'],
    };
}

export function LoginAuthCodeVerifiedResultToJSON(value?: LoginAuthCodeVerifiedResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'refreshToken': value.refreshToken,
    };
}

