/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.556+c0267cc6
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DefinitionChange } from './DefinitionChange';
import {
    DefinitionChangeFromJSON,
    DefinitionChangeFromJSONTyped,
    DefinitionChangeToJSON,
} from './DefinitionChange';
import type { SubmissionChange } from './SubmissionChange';
import {
    SubmissionChangeFromJSON,
    SubmissionChangeFromJSONTyped,
    SubmissionChangeToJSON,
} from './SubmissionChange';

/**
 * 
 * @export
 * @interface MergeChangesetCommand
 */
export interface MergeChangesetCommand {
    /**
     * 
     * @type {string}
     * @memberof MergeChangesetCommand
     */
    uuid?: string;
    /**
     * 
     * @type {Array<DefinitionChange>}
     * @memberof MergeChangesetCommand
     */
    definitionChanges: Array<DefinitionChange>;
    /**
     * 
     * @type {Array<SubmissionChange>}
     * @memberof MergeChangesetCommand
     */
    submissionChanges: Array<SubmissionChange>;
}

/**
 * Check if a given object implements the MergeChangesetCommand interface.
 */
export function instanceOfMergeChangesetCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "definitionChanges" in value;
    isInstance = isInstance && "submissionChanges" in value;

    return isInstance;
}

export function MergeChangesetCommandFromJSON(json: any): MergeChangesetCommand {
    return MergeChangesetCommandFromJSONTyped(json, false);
}

export function MergeChangesetCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeChangesetCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'definitionChanges': ((json['definitionChanges'] as Array<any>).map(DefinitionChangeFromJSON)),
        'submissionChanges': ((json['submissionChanges'] as Array<any>).map(SubmissionChangeFromJSON)),
    };
}

export function MergeChangesetCommandToJSON(value?: MergeChangesetCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'definitionChanges': ((value.definitionChanges as Array<any>).map(DefinitionChangeToJSON)),
        'submissionChanges': ((value.submissionChanges as Array<any>).map(SubmissionChangeToJSON)),
    };
}

