/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestLoginAuthCodeCommand
 */
export interface RequestLoginAuthCodeCommand {
    /**
     * 
     * @type {string}
     * @memberof RequestLoginAuthCodeCommand
     */
    userEmailAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestLoginAuthCodeCommand
     */
    fairUseToken?: string | null;
}

/**
 * Check if a given object implements the RequestLoginAuthCodeCommand interface.
 */
export function instanceOfRequestLoginAuthCodeCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestLoginAuthCodeCommandFromJSON(json: any): RequestLoginAuthCodeCommand {
    return RequestLoginAuthCodeCommandFromJSONTyped(json, false);
}

export function RequestLoginAuthCodeCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestLoginAuthCodeCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userEmailAddress': !exists(json, 'userEmailAddress') ? undefined : json['userEmailAddress'],
        'fairUseToken': !exists(json, 'fairUseToken') ? undefined : json['fairUseToken'],
    };
}

export function RequestLoginAuthCodeCommandToJSON(value?: RequestLoginAuthCodeCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userEmailAddress': value.userEmailAddress,
        'fairUseToken': value.fairUseToken,
    };
}

