/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.556+c0267cc6
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SubmissionSummary } from './SubmissionSummary';
import {
    SubmissionSummaryFromJSON,
    SubmissionSummaryFromJSONTyped,
    SubmissionSummaryToJSON,
} from './SubmissionSummary';

/**
 * 
 * @export
 * @interface SubmissionSummaryPagedResult
 */
export interface SubmissionSummaryPagedResult {
    /**
     * 
     * @type {Array<SubmissionSummary>}
     * @memberof SubmissionSummaryPagedResult
     */
    items: Array<SubmissionSummary>;
    /**
     * 
     * @type {number}
     * @memberof SubmissionSummaryPagedResult
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof SubmissionSummaryPagedResult
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof SubmissionSummaryPagedResult
     */
    totalCount: number;
}

/**
 * Check if a given object implements the SubmissionSummaryPagedResult interface.
 */
export function instanceOfSubmissionSummaryPagedResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "pageNumber" in value;
    isInstance = isInstance && "totalCount" in value;

    return isInstance;
}

export function SubmissionSummaryPagedResultFromJSON(json: any): SubmissionSummaryPagedResult {
    return SubmissionSummaryPagedResultFromJSONTyped(json, false);
}

export function SubmissionSummaryPagedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionSummaryPagedResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SubmissionSummaryFromJSON)),
        'pageSize': json['pageSize'],
        'pageNumber': json['pageNumber'],
        'totalCount': json['totalCount'],
    };
}

export function SubmissionSummaryPagedResultToJSON(value?: SubmissionSummaryPagedResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(SubmissionSummaryToJSON)),
        'pageSize': value.pageSize,
        'pageNumber': value.pageNumber,
        'totalCount': value.totalCount,
    };
}

