/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.556+c0267cc6
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DefinitionDetails } from './DefinitionDetails';
import {
    DefinitionDetailsFromJSON,
    DefinitionDetailsFromJSONTyped,
    DefinitionDetailsToJSON,
} from './DefinitionDetails';

/**
 * 
 * @export
 * @interface SubmissionDetails
 */
export interface SubmissionDetails {
    /**
     * 
     * @type {string}
     * @memberof SubmissionDetails
     */
    uuid: string;
    /**
     * 
     * @type {Date}
     * @memberof SubmissionDetails
     */
    timestamp: Date;
    /**
     * 
     * @type {DefinitionDetails}
     * @memberof SubmissionDetails
     */
    definition: DefinitionDetails;
    /**
     * 
     * @type {string}
     * @memberof SubmissionDetails
     */
    contents: string;
}

/**
 * Check if a given object implements the SubmissionDetails interface.
 */
export function instanceOfSubmissionDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "definition" in value;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function SubmissionDetailsFromJSON(json: any): SubmissionDetails {
    return SubmissionDetailsFromJSONTyped(json, false);
}

export function SubmissionDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'timestamp': (new Date(json['timestamp'])),
        'definition': DefinitionDetailsFromJSON(json['definition']),
        'contents': json['contents'],
    };
}

export function SubmissionDetailsToJSON(value?: SubmissionDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'timestamp': (value.timestamp.toISOString()),
        'definition': DefinitionDetailsToJSON(value.definition),
        'contents': value.contents,
    };
}

