/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DefinitionSummary } from './DefinitionSummary';
import {
    DefinitionSummaryFromJSON,
    DefinitionSummaryFromJSONTyped,
    DefinitionSummaryToJSON,
} from './DefinitionSummary';

/**
 * 
 * @export
 * @interface SubmissionSummary
 */
export interface SubmissionSummary {
    /**
     * 
     * @type {string}
     * @memberof SubmissionSummary
     */
    uuid: string;
    /**
     * 
     * @type {DefinitionSummary}
     * @memberof SubmissionSummary
     */
    definition: DefinitionSummary;
}

/**
 * Check if a given object implements the SubmissionSummary interface.
 */
export function instanceOfSubmissionSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "definition" in value;

    return isInstance;
}

export function SubmissionSummaryFromJSON(json: any): SubmissionSummary {
    return SubmissionSummaryFromJSONTyped(json, false);
}

export function SubmissionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'definition': DefinitionSummaryFromJSON(json['definition']),
    };
}

export function SubmissionSummaryToJSON(value?: SubmissionSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'definition': DefinitionSummaryToJSON(value.definition),
    };
}

