/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DefinitionSummary } from './DefinitionSummary';
import {
    DefinitionSummaryFromJSON,
    DefinitionSummaryFromJSONTyped,
    DefinitionSummaryToJSON,
} from './DefinitionSummary';

/**
 * 
 * @export
 * @interface SubmissionDetails
 */
export interface SubmissionDetails {
    /**
     * 
     * @type {string}
     * @memberof SubmissionDetails
     */
    uuid: string;
    /**
     * 
     * @type {DefinitionSummary}
     * @memberof SubmissionDetails
     */
    definition: DefinitionSummary;
    /**
     * 
     * @type {string}
     * @memberof SubmissionDetails
     */
    contents: string;
}

/**
 * Check if a given object implements the SubmissionDetails interface.
 */
export function instanceOfSubmissionDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "definition" in value;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function SubmissionDetailsFromJSON(json: any): SubmissionDetails {
    return SubmissionDetailsFromJSONTyped(json, false);
}

export function SubmissionDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'definition': DefinitionSummaryFromJSON(json['definition']),
        'contents': json['contents'],
    };
}

export function SubmissionDetailsToJSON(value?: SubmissionDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'definition': DefinitionSummaryToJSON(value.definition),
        'contents': value.contents,
    };
}

