/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.559+e6531977
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChangeStatus } from './ChangeStatus';
import {
    ChangeStatusFromJSON,
    ChangeStatusFromJSONTyped,
    ChangeStatusToJSON,
} from './ChangeStatus';

/**
 * 
 * @export
 * @interface SubmissionChange
 */
export interface SubmissionChange {
    /**
     * 
     * @type {string}
     * @memberof SubmissionChange
     */
    uuid: string;
    /**
     * 
     * @type {Date}
     * @memberof SubmissionChange
     */
    timestamp: Date;
    /**
     * 
     * @type {ChangeStatus}
     * @memberof SubmissionChange
     */
    changeStatus: ChangeStatus;
    /**
     * 
     * @type {string}
     * @memberof SubmissionChange
     */
    definitionUuid: string;
    /**
     * 
     * @type {string}
     * @memberof SubmissionChange
     */
    contents: string;
}

/**
 * Check if a given object implements the SubmissionChange interface.
 */
export function instanceOfSubmissionChange(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "changeStatus" in value;
    isInstance = isInstance && "definitionUuid" in value;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function SubmissionChangeFromJSON(json: any): SubmissionChange {
    return SubmissionChangeFromJSONTyped(json, false);
}

export function SubmissionChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionChange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'timestamp': (new Date(json['timestamp'])),
        'changeStatus': ChangeStatusFromJSON(json['changeStatus']),
        'definitionUuid': json['definitionUuid'],
        'contents': json['contents'],
    };
}

export function SubmissionChangeToJSON(value?: SubmissionChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'timestamp': (value.timestamp.toISOString()),
        'changeStatus': ChangeStatusToJSON(value.changeStatus),
        'definitionUuid': value.definitionUuid,
        'contents': value.contents,
    };
}

