/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SubmissionSummary } from './SubmissionSummary';
import {
    SubmissionSummaryFromJSON,
    SubmissionSummaryFromJSONTyped,
    SubmissionSummaryToJSON,
} from './SubmissionSummary';

/**
 * 
 * @export
 * @interface SubmissionSummaryPagedResult
 */
export interface SubmissionSummaryPagedResult {
    /**
     * 
     * @type {Array<SubmissionSummary>}
     * @memberof SubmissionSummaryPagedResult
     */
    items?: Array<SubmissionSummary> | null;
    /**
     * 
     * @type {number}
     * @memberof SubmissionSummaryPagedResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof SubmissionSummaryPagedResult
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof SubmissionSummaryPagedResult
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the SubmissionSummaryPagedResult interface.
 */
export function instanceOfSubmissionSummaryPagedResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubmissionSummaryPagedResultFromJSON(json: any): SubmissionSummaryPagedResult {
    return SubmissionSummaryPagedResultFromJSONTyped(json, false);
}

export function SubmissionSummaryPagedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionSummaryPagedResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(SubmissionSummaryFromJSON)),
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
    };
}

export function SubmissionSummaryPagedResultToJSON(value?: SubmissionSummaryPagedResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(SubmissionSummaryToJSON)),
        'pageSize': value.pageSize,
        'pageNumber': value.pageNumber,
        'totalCount': value.totalCount,
    };
}

