/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.496+a2635268
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantDetails
 */
export interface TenantDetails {
    /**
     * 
     * @type {string}
     * @memberof TenantDetails
     */
    uuid: string;
}

/**
 * Check if a given object implements the TenantDetails interface.
 */
export function instanceOfTenantDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;

    return isInstance;
}

export function TenantDetailsFromJSON(json: any): TenantDetails {
    return TenantDetailsFromJSONTyped(json, false);
}

export function TenantDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
    };
}

export function TenantDetailsToJSON(value?: TenantDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
    };
}

