/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TenantDetails } from './TenantDetails';
import {
    TenantDetailsFromJSON,
    TenantDetailsFromJSONTyped,
    TenantDetailsToJSON,
} from './TenantDetails';

/**
 * 
 * @export
 * @interface TenantDetailsPagedResult
 */
export interface TenantDetailsPagedResult {
    /**
     * 
     * @type {Array<TenantDetails>}
     * @memberof TenantDetailsPagedResult
     */
    items?: Array<TenantDetails> | null;
    /**
     * 
     * @type {number}
     * @memberof TenantDetailsPagedResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TenantDetailsPagedResult
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof TenantDetailsPagedResult
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the TenantDetailsPagedResult interface.
 */
export function instanceOfTenantDetailsPagedResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TenantDetailsPagedResultFromJSON(json: any): TenantDetailsPagedResult {
    return TenantDetailsPagedResultFromJSONTyped(json, false);
}

export function TenantDetailsPagedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDetailsPagedResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(TenantDetailsFromJSON)),
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
    };
}

export function TenantDetailsPagedResultToJSON(value?: TenantDetailsPagedResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(TenantDetailsToJSON)),
        'pageSize': value.pageSize,
        'pageNumber': value.pageNumber,
        'totalCount': value.totalCount,
    };
}

