/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.461+9159d8a8
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TenantDetails } from './TenantDetails';
import {
    TenantDetailsFromJSON,
    TenantDetailsFromJSONTyped,
    TenantDetailsToJSON,
} from './TenantDetails';

/**
 * 
 * @export
 * @interface TenantDetailsPagedResult
 */
export interface TenantDetailsPagedResult {
    /**
     * 
     * @type {Array<TenantDetails>}
     * @memberof TenantDetailsPagedResult
     */
    items: Array<TenantDetails>;
    /**
     * 
     * @type {number}
     * @memberof TenantDetailsPagedResult
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof TenantDetailsPagedResult
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof TenantDetailsPagedResult
     */
    totalCount: number;
}

/**
 * Check if a given object implements the TenantDetailsPagedResult interface.
 */
export function instanceOfTenantDetailsPagedResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "pageNumber" in value;
    isInstance = isInstance && "totalCount" in value;

    return isInstance;
}

export function TenantDetailsPagedResultFromJSON(json: any): TenantDetailsPagedResult {
    return TenantDetailsPagedResultFromJSONTyped(json, false);
}

export function TenantDetailsPagedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDetailsPagedResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TenantDetailsFromJSON)),
        'pageSize': json['pageSize'],
        'pageNumber': json['pageNumber'],
        'totalCount': json['totalCount'],
    };
}

export function TenantDetailsPagedResultToJSON(value?: TenantDetailsPagedResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(TenantDetailsToJSON)),
        'pageSize': value.pageSize,
        'pageNumber': value.pageNumber,
        'totalCount': value.totalCount,
    };
}

