/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.556+c0267cc6
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserTenantElement
 */
export interface UserTenantElement {
    /**
     * 
     * @type {string}
     * @memberof UserTenantElement
     */
    tenantUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTenantElement
     */
    tenantName?: string | null;
}

/**
 * Check if a given object implements the UserTenantElement interface.
 */
export function instanceOfUserTenantElement(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserTenantElementFromJSON(json: any): UserTenantElement {
    return UserTenantElementFromJSONTyped(json, false);
}

export function UserTenantElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTenantElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tenantUuid': !exists(json, 'tenantUuid') ? undefined : json['tenantUuid'],
        'tenantName': !exists(json, 'tenantName') ? undefined : json['tenantName'],
    };
}

export function UserTenantElementToJSON(value?: UserTenantElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tenantUuid': value.tenantUuid,
        'tenantName': value.tenantName,
    };
}

