/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.461+9159d8a8
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserTenantElement } from './UserTenantElement';
import {
    UserTenantElementFromJSON,
    UserTenantElementFromJSONTyped,
    UserTenantElementToJSON,
} from './UserTenantElement';

/**
 * 
 * @export
 * @interface UserDetails
 */
export interface UserDetails {
    /**
     * 
     * @type {string}
     * @memberof UserDetails
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetails
     */
    emailAddress: string;
    /**
     * 
     * @type {Array<UserTenantElement>}
     * @memberof UserDetails
     */
    tenants: Array<UserTenantElement>;
}

/**
 * Check if a given object implements the UserDetails interface.
 */
export function instanceOfUserDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "emailAddress" in value;
    isInstance = isInstance && "tenants" in value;

    return isInstance;
}

export function UserDetailsFromJSON(json: any): UserDetails {
    return UserDetailsFromJSONTyped(json, false);
}

export function UserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'emailAddress': json['emailAddress'],
        'tenants': ((json['tenants'] as Array<any>).map(UserTenantElementFromJSON)),
    };
}

export function UserDetailsToJSON(value?: UserDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'emailAddress': value.emailAddress,
        'tenants': ((value.tenants as Array<any>).map(UserTenantElementToJSON)),
    };
}

