/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.496+a2635268
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationProblemDetails
 */
export interface ValidationProblemDetails {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ValidationProblemDetails
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationProblemDetails
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ValidationProblemDetails
     */
    status?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationProblemDetails
     */
    detail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationProblemDetails
     */
    instance?: string | null;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ValidationProblemDetails
     */
    errors?: { [key: string]: Array<string>; } | null;
}

/**
 * Check if a given object implements the ValidationProblemDetails interface.
 */
export function instanceOfValidationProblemDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ValidationProblemDetailsFromJSON(json: any): ValidationProblemDetails {
    return ValidationProblemDetailsFromJSONTyped(json, false);
}

export function ValidationProblemDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationProblemDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'type': !exists(json, 'type') ? undefined : json['type'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'detail': !exists(json, 'detail') ? undefined : json['detail'],
        'instance': !exists(json, 'instance') ? undefined : json['instance'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function ValidationProblemDetailsToJSON(value?: ValidationProblemDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'type': value.type,
        'title': value.title,
        'status': value.status,
        'detail': value.detail,
        'instance': value.instance,
        'errors': value.errors,
    };
}

