/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.559+e6531977
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyLoginAuthCodeCommand
 */
export interface VerifyLoginAuthCodeCommand {
    /**
     * 
     * @type {string}
     * @memberof VerifyLoginAuthCodeCommand
     */
    userEmailAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VerifyLoginAuthCodeCommand
     */
    fairUseToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VerifyLoginAuthCodeCommand
     */
    authCode?: string | null;
}

/**
 * Check if a given object implements the VerifyLoginAuthCodeCommand interface.
 */
export function instanceOfVerifyLoginAuthCodeCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VerifyLoginAuthCodeCommandFromJSON(json: any): VerifyLoginAuthCodeCommand {
    return VerifyLoginAuthCodeCommandFromJSONTyped(json, false);
}

export function VerifyLoginAuthCodeCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyLoginAuthCodeCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userEmailAddress': !exists(json, 'userEmailAddress') ? undefined : json['userEmailAddress'],
        'fairUseToken': !exists(json, 'fairUseToken') ? undefined : json['fairUseToken'],
        'authCode': !exists(json, 'authCode') ? undefined : json['authCode'],
    };
}

export function VerifyLoginAuthCodeCommandToJSON(value?: VerifyLoginAuthCodeCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userEmailAddress': value.userEmailAddress,
        'fairUseToken': value.fairUseToken,
        'authCode': value.authCode,
    };
}

