/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppVersion,
  HealthReport,
} from '../models/index';
import {
    AppVersionFromJSON,
    AppVersionToJSON,
    HealthReportFromJSON,
    HealthReportToJSON,
} from '../models/index';

/**
 * 
 */
export class AppInfoApiClient extends runtime.BaseAPI {

    /**
     * Checks application health.
     */
    async checkAppHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthReport>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthReportFromJSON(jsonValue));
    }

    /**
     * Checks application health.
     */
    async checkAppHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthReport> {
        const response = await this.checkAppHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns a ZIP archive containing application source code.
     */
    async getAppSourceCodeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/source-code`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns a ZIP archive containing application source code.
     */
    async getAppSourceCode(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAppSourceCodeRaw(initOverrides);
    }

    /**
     * Returns application version.
     */
    async getAppVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppVersion>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/version`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppVersionFromJSON(jsonValue));
    }

    /**
     * Returns application version.
     */
    async getAppVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppVersion> {
        const response = await this.getAppVersionRaw(initOverrides);
        return await response.value();
    }

}
