/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDefinitionCommand,
  CreateSubmissionCommand,
  DefinitionDetails,
  DefinitionSummaryPagedResult,
  ProblemDetails,
  SubmissionDetails,
  SubmissionSummaryPagedResult,
} from '../models/index';
import {
    CreateDefinitionCommandFromJSON,
    CreateDefinitionCommandToJSON,
    CreateSubmissionCommandFromJSON,
    CreateSubmissionCommandToJSON,
    DefinitionDetailsFromJSON,
    DefinitionDetailsToJSON,
    DefinitionSummaryPagedResultFromJSON,
    DefinitionSummaryPagedResultToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SubmissionDetailsFromJSON,
    SubmissionDetailsToJSON,
    SubmissionSummaryPagedResultFromJSON,
    SubmissionSummaryPagedResultToJSON,
} from '../models/index';

export interface CreateDefinitionV1Request {
    createDefinitionCommand: CreateDefinitionCommand;
}

export interface CreateSubmissionV1Request {
    createSubmissionCommand: CreateSubmissionCommand;
}

export interface ReadDefinitionV1Request {
    uuid: string;
}

export interface ReadDefinitionsV1Request {
    pageSize: number;
    pageNumber: number;
}

export interface ReadSubmissionV1Request {
    uuid: string;
}

export interface ReadSubmissionsV1Request {
    pageSize: number;
    pageNumber: number;
}

/**
 * 
 */
export class ChecklistsApiClient extends runtime.BaseAPI {

    /**
     */
    async createDefinitionV1Raw(requestParameters: CreateDefinitionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.createDefinitionCommand === null || requestParameters.createDefinitionCommand === undefined) {
            throw new runtime.RequiredError('createDefinitionCommand','Required parameter requestParameters.createDefinitionCommand was null or undefined when calling createDefinitionV1.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/checklists/definitions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDefinitionCommandToJSON(requestParameters.createDefinitionCommand),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createDefinitionV1(requestParameters: CreateDefinitionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createDefinitionV1Raw(requestParameters, initOverrides);
    }

    /**
     */
    async createSubmissionV1Raw(requestParameters: CreateSubmissionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.createSubmissionCommand === null || requestParameters.createSubmissionCommand === undefined) {
            throw new runtime.RequiredError('createSubmissionCommand','Required parameter requestParameters.createSubmissionCommand was null or undefined when calling createSubmissionV1.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/checklists/submissions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSubmissionCommandToJSON(requestParameters.createSubmissionCommand),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createSubmissionV1(requestParameters: CreateSubmissionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createSubmissionV1Raw(requestParameters, initOverrides);
    }

    /**
     */
    async readDefinitionV1Raw(requestParameters: ReadDefinitionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DefinitionDetails>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling readDefinitionV1.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/checklists/definitions/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DefinitionDetailsFromJSON(jsonValue));
    }

    /**
     */
    async readDefinitionV1(requestParameters: ReadDefinitionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DefinitionDetails> {
        const response = await this.readDefinitionV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readDefinitionsV1Raw(requestParameters: ReadDefinitionsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DefinitionSummaryPagedResult>> {
        if (requestParameters.pageSize === null || requestParameters.pageSize === undefined) {
            throw new runtime.RequiredError('pageSize','Required parameter requestParameters.pageSize was null or undefined when calling readDefinitionsV1.');
        }

        if (requestParameters.pageNumber === null || requestParameters.pageNumber === undefined) {
            throw new runtime.RequiredError('pageNumber','Required parameter requestParameters.pageNumber was null or undefined when calling readDefinitionsV1.');
        }

        const queryParameters: any = {};

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.pageNumber !== undefined) {
            queryParameters['pageNumber'] = requestParameters.pageNumber;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/checklists/definitions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DefinitionSummaryPagedResultFromJSON(jsonValue));
    }

    /**
     */
    async readDefinitionsV1(requestParameters: ReadDefinitionsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DefinitionSummaryPagedResult> {
        const response = await this.readDefinitionsV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readSubmissionV1Raw(requestParameters: ReadSubmissionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmissionDetails>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling readSubmissionV1.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/checklists/submissions/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionDetailsFromJSON(jsonValue));
    }

    /**
     */
    async readSubmissionV1(requestParameters: ReadSubmissionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmissionDetails> {
        const response = await this.readSubmissionV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readSubmissionsV1Raw(requestParameters: ReadSubmissionsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmissionSummaryPagedResult>> {
        if (requestParameters.pageSize === null || requestParameters.pageSize === undefined) {
            throw new runtime.RequiredError('pageSize','Required parameter requestParameters.pageSize was null or undefined when calling readSubmissionsV1.');
        }

        if (requestParameters.pageNumber === null || requestParameters.pageNumber === undefined) {
            throw new runtime.RequiredError('pageNumber','Required parameter requestParameters.pageNumber was null or undefined when calling readSubmissionsV1.');
        }

        const queryParameters: any = {};

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.pageNumber !== undefined) {
            queryParameters['pageNumber'] = requestParameters.pageNumber;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/checklists/submissions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionSummaryPagedResultFromJSON(jsonValue));
    }

    /**
     */
    async readSubmissionsV1(requestParameters: ReadSubmissionsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmissionSummaryPagedResult> {
        const response = await this.readSubmissionsV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
