/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.461+9159d8a8
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FairUseToken,
} from '../models/index';
import {
    FairUseTokenFromJSON,
    FairUseTokenToJSON,
} from '../models/index';

/**
 * 
 */
export class FairUseTokenApiClient extends runtime.BaseAPI {

    /**
     * Generates and returns an encrypted fair use token.
     */
    async getFairUseTokenV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FairUseToken>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/fair-use-token`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FairUseTokenFromJSON(jsonValue));
    }

    /**
     * Generates and returns an encrypted fair use token.
     */
    async getFairUseTokenV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FairUseToken> {
        const response = await this.getFairUseTokenV1Raw(initOverrides);
        return await response.value();
    }

}
