/* tslint:disable */
/* eslint-disable */
/**
 * LibreCheck API
 * TODO  Some useful links: - [API source code](https://gitlab.com/librecheck-io/librecheck-api) - [Reference App source code](https://gitlab.com/librecheck-io/librecheck-app)
 *
 * The version of the OpenAPI document: 0.496+a2635268
 * Contact: hello@librecheck.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoginAuthCodeVerifiedResult,
  RequestLoginAuthCodeCommand,
  TenantDetailsPagedResult,
  UserDetails,
  ValidationProblemDetails,
  VerifyLoginAuthCodeCommand,
} from '../models/index';
import {
    LoginAuthCodeVerifiedResultFromJSON,
    LoginAuthCodeVerifiedResultToJSON,
    RequestLoginAuthCodeCommandFromJSON,
    RequestLoginAuthCodeCommandToJSON,
    TenantDetailsPagedResultFromJSON,
    TenantDetailsPagedResultToJSON,
    UserDetailsFromJSON,
    UserDetailsToJSON,
    ValidationProblemDetailsFromJSON,
    ValidationProblemDetailsToJSON,
    VerifyLoginAuthCodeCommandFromJSON,
    VerifyLoginAuthCodeCommandToJSON,
} from '../models/index';

export interface GetTenantsV1Request {
    pageSize: number;
    pageNumber: number;
}

export interface RequestLoginAuthCodeV1Request {
    requestLoginAuthCodeCommand: RequestLoginAuthCodeCommand;
}

export interface VerifyLoginAuthCodeV1Request {
    verifyLoginAuthCodeCommand: VerifyLoginAuthCodeCommand;
}

/**
 * 
 */
export class IamApiClient extends runtime.BaseAPI {

    /**
     */
    async getCurrentUserV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/iam/users/current`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDetailsFromJSON(jsonValue));
    }

    /**
     */
    async getCurrentUserV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDetails> {
        const response = await this.getCurrentUserV1Raw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getTenantsV1Raw(requestParameters: GetTenantsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantDetailsPagedResult>> {
        if (requestParameters.pageSize === null || requestParameters.pageSize === undefined) {
            throw new runtime.RequiredError('pageSize','Required parameter requestParameters.pageSize was null or undefined when calling getTenantsV1.');
        }

        if (requestParameters.pageNumber === null || requestParameters.pageNumber === undefined) {
            throw new runtime.RequiredError('pageNumber','Required parameter requestParameters.pageNumber was null or undefined when calling getTenantsV1.');
        }

        const queryParameters: any = {};

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.pageNumber !== undefined) {
            queryParameters['pageNumber'] = requestParameters.pageNumber;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/iam/tenants`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantDetailsPagedResultFromJSON(jsonValue));
    }

    /**
     */
    async getTenantsV1(requestParameters: GetTenantsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantDetailsPagedResult> {
        const response = await this.getTenantsV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async requestLoginAuthCodeV1Raw(requestParameters: RequestLoginAuthCodeV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.requestLoginAuthCodeCommand === null || requestParameters.requestLoginAuthCodeCommand === undefined) {
            throw new runtime.RequiredError('requestLoginAuthCodeCommand','Required parameter requestParameters.requestLoginAuthCodeCommand was null or undefined when calling requestLoginAuthCodeV1.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/iam/login/request-auth-code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestLoginAuthCodeCommandToJSON(requestParameters.requestLoginAuthCodeCommand),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async requestLoginAuthCodeV1(requestParameters: RequestLoginAuthCodeV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestLoginAuthCodeV1Raw(requestParameters, initOverrides);
    }

    /**
     */
    async verifyLoginAuthCodeV1Raw(requestParameters: VerifyLoginAuthCodeV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginAuthCodeVerifiedResult>> {
        if (requestParameters.verifyLoginAuthCodeCommand === null || requestParameters.verifyLoginAuthCodeCommand === undefined) {
            throw new runtime.RequiredError('verifyLoginAuthCodeCommand','Required parameter requestParameters.verifyLoginAuthCodeCommand was null or undefined when calling verifyLoginAuthCodeV1.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/iam/login/verify-auth-code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyLoginAuthCodeCommandToJSON(requestParameters.verifyLoginAuthCodeCommand),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginAuthCodeVerifiedResultFromJSON(jsonValue));
    }

    /**
     */
    async verifyLoginAuthCodeV1(requestParameters: VerifyLoginAuthCodeV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginAuthCodeVerifiedResult> {
        const response = await this.verifyLoginAuthCodeV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
